name: CI test to build and run tests for MYNN EDMF scheme on ubuntu v22.04

on: [pull_request,workflow_dispatch,push]

jobs:
  run_driver:

    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        fortran-compiler: [gfortran-12]

    # Environmental variables
    env:
      NFHOME:      /usr
      NFVERSION:   v4.5.3
      driver_ROOT: /home/runner/work/MYNN-EDMF/MYNN-EDMF

    # Workflow steps
    steps:

    - name: Checkout code (into ${driver_ROOT})
      uses: actions/checkout@v3

    # NetCDF C and FORTRAN libraries
    - name: Install NetCDF library
      run: |
        sudo apt-get update
        sudo apt-get install libnetcdff-dev

    - name: Build unit tests
      run: |
        cd ${driver_ROOT}/tests
        make driver

    - name: Run unit tests
      run: |
        cd ${driver_ROOT}/tests
        ./driver
